"""scaffold: `homelab-maint new task|job|probe NAME` generators and SECURE plugin discovery (SPEC4 S11).

GENERATORS (render_* are pure; create() writes)
  new task NAME   a ready-to-edit task module (C0 read-only | C1 safe cleaner through ctx.act | C2 plan + approval) and a test stub
  new job NAME    a jobs.toml [[job]] snippet (an external command the scheduler runs, gates, logs and reports)
  new probe NAME  a probes.toml [[probe]] snippet (http | tcp | docker | systemd | command | file_age | json)
  Nothing is written outside --out unless --install, which targets <conf>/plugins.d (tasks), <conf>/jobs.d and <conf>/probes.d
  (snippets) and is REFUSED when this build's loader does not read that directory (loader_reads: a file nothing picks up would look
  installed and never run). Files are created O_EXCL|O_NOFOLLOW (never overwrite, never follow a planted symlink), names are validated,
  and every generated Python file is compiled and every TOML snippet parsed before it is written, so what you get always loads (the
  tests also load every generated job and probe through the real scheduler and probe engine).

PLUGIN DISCOVERY (load_plugins; the glue calls it from cli.load_tasks)
  /etc/homelab-maint/plugins.d/*.py are ROOT CODE: whoever can write there owns the box. So a plugin is executed only when
    * the directory (and every ancestor) is a real directory owned by root (or the runner), not group/world-writable
      (sticky dirs such as /tmp are tolerated as ancestors only),
    * the file is a regular file (a symlink is refused even if root-owned), owned by root (or the runner), not group/world
      writable, <= 256 KiB, with a plain module-name file name,
    * the bytes that are compiled are the bytes of the file descriptor that passed those checks (O_NOFOLLOW, fstat compared with
      lstat: no check-then-open race).
  A plugin is isolated: its import is guarded by a timeout, any exception (SyntaxError, ImportError, SystemExit, a hung import)
  rolls back whatever it registered and is reported as a registered `plugin_<stem>` task whose result is `error`, so the owner
  sees it in status.json and gets paged, and every other plugin and builtin still runs. A plugin can never REPLACE or remove a
  builtin task (the registry entry is restored and the attempt is reported), and registered tasks are validated (name, class,
  tier, callable, timeout) before they are kept. An insecure directory refuses all plugins and registers `plugins_dir`.
"""
from __future__ import annotations

import contextlib
import os
import re
import signal
import stat
import sys
import threading
import tomllib
import types
from dataclasses import dataclass, field
from pathlib import Path
from string import Template
from typing import Any

from . import core
from .core import Result, Task

TASK_RX = re.compile(r"[a-z][a-z0-9_]{1,39}")
NAME_RX = re.compile(r"[a-z0-9][a-z0-9_.-]{0,47}")
PLUGIN_FILE_RX = re.compile(r"[A-Za-z][A-Za-z0-9_]{0,59}\.py")
KLASSES = ("C0", "C1", "C2")
TIERS = ("check", "daily", "weekly")
PROBE_TYPES = ("http", "tcp", "docker", "systemd", "command", "file_age", "json")
MAX_PLUGIN_BYTES = 256 * 1024
IMPORT_TIMEOUT_S = 5.0


# =================================================================== templates
_TASK_HEAD = '''"""$name: $title.

Generated by `homelab-maint new task $name` (class $klass, tier $tier). Where it lives:
  * an owner plugin: copy to /etc/homelab-maint/plugins.d/$name.py (root-owned, mode 0644; the directory root-owned 0755 and not
    group/world-writable, or it is refused). It is discovered on the next run. A plugin is root code: review it like sudo.
  * part of the package: move to homelab_maint/tasks/$name.py (auto-imported) and add tests/test_$name.py.
Options live in /etc/homelab-maint/maint.toml under [tasks.$name] and are read with ctx.opt("key", default).
Rules: every Result.summary is ONE ASCII line of at most 140 characters (it can become an SMS); an unreadable probe, a timeout or an
empty selector means "do nothing" (fail closed); never print or store a secret.
"""
from homelab_maint.core import Ctx, Result, task
'''

_TASK_C0 = _TASK_HEAD + '''import os


@task("$name", klass="C0", tier="$tier", title="$title", timeout=60)
def run(ctx: Ctx) -> Result:
    """C0 = read-only by construction: the runner forces apply off, so this can only look."""
    warn_at = float(ctx.opt("warn_load", 50.0))        # [tasks.$name] warn_load = 50.0
    try:
        load1 = os.getloadavg()[0]                      # replace with what you actually want to watch
    except OSError:
        return Result("warn", "$title: cannot read the load average")      # fail closed: unknown is a problem, not "fine"
    status = "warn" if load1 >= warn_at else "ok"
    return Result(status, f"$title: load {load1:.1f} (warn at {warn_at:g})", metrics={"load1": round(load1, 2)})
'''

_TASK_C1 = _TASK_HEAD + '''import os

from homelab_maint.core import human


@task("$name", klass="C1", tier="$tier", title="$title", timeout=300)
def run(ctx: Ctx) -> Result:
    """C1 = safe auto-clean. It mutates ONLY through ctx.act, and ctx.apply is false unless [tasks.$name] mode = "apply" AND the
    run was started with --apply AND no PAUSE file exists. In report mode ctx.act audits "dry-run" and returns False, so the
    dry-run list is exactly what apply mode would do. Ship it in report mode and flip it after reading a few days of output."""
    path = str(ctx.opt("path", ""))                     # [tasks.$name] path = "/some/dir"; unset selects NOTHING
    days = float(ctx.opt("max_age_days", 30))
    if not path or not os.path.isdir(path):
        return Result("skipped", "$title: no valid path configured, nothing selected", alert=False)
    victims = []
    for e in os.scandir(path):                           # one level, never follows symlinks
        if e.is_file(follow_symlinks=False) and ctx.now - e.stat(follow_symlinks=False).st_mtime > days * 86400:
            victims.append((e.path, e.stat(follow_symlinks=False).st_size))
    victims.sort()                                       # stable order => stable dry-run output
    for p, size in victims:
        # ctx.act refuses empty targets, protected paths (protected.toml) and per-run caps, and audits every attempt
        ctx.act("delete", p, size, lambda p=p: os.unlink(p), protect_names=(os.path.basename(p),))
    total = sum(s for _p, s in victims)
    verb = "removed" if ctx.apply else "would remove"
    return Result("ok", f"$title: {verb} {len(victims)} file(s), {human(total)}", metrics={"files": len(victims), "bytes": total},
                  items=[{"path": p, "bytes": s} for p, s in victims[:12]], alert=False)
'''

_TASK_C2 = _TASK_HEAD + '''import os

from homelab_maint import core


@task("$name", klass="C2", tier="$tier", title="$title", timeout=300)
def run(ctx: Ctx) -> Result:
    """C2 = plan only. It returns Result(plan=...); `homelab-maint plan $name` shows the plan hash and
    `homelab-maint approve $name HASH` re-plans, writes the approval and runs with apply on. Nothing mutates without that file."""
    wanted = [p for p in ctx.opt("candidates", []) if isinstance(p, str) and p.startswith("/")]   # [tasks.$name] candidates = [...]
    items = sorted(({"name": p, "bytes": os.path.getsize(p)} for p in wanted if os.path.isfile(p)), key=lambda i: i["name"])
    plan = {"items": items, "total_bytes": sum(i["bytes"] for i in items)}      # stable ordering => stable hash
    h = core.plan_hash(plan)
    res = Result("info" if items else "ok", f"$title: {len(items)} candidate(s); plan {h}", {"plan_hash": h}, items[:12], plan=plan, alert=False)
    if not (ctx.apply and items) or not core.approved(ctx.name, h):
        return res
    for it in items:
        ctx.act("delete", it["name"], it["bytes"], lambda p=it["name"]: os.unlink(p))
    return res
'''

_TEST_STUB = '''"""Test stub for the $name task. Run from the repository: python3 -m pytest tests/test_$name.py -q"""
import conftest  # noqa: F401  (points HOMELAB_MAINT_* at tmp dirs BEFORE homelab_maint.core is imported)

import importlib.util
import pathlib
import subprocess

import pytest

from homelab_maint import core
from homelab_maint.core import Ctx

HERE = pathlib.Path(__file__).resolve().parent


@pytest.fixture(autouse=True)
def _no_syslog(monkeypatch):
    """ctx.act audits through `logger`; keep tests from writing to the real syslog."""
    monkeypatch.setattr(core, "sh", lambda *a, **k: subprocess.CompletedProcess(a, 0, "", ""))


def load():
    try:
        from homelab_maint.tasks import $name as mod      # once you moved it into the package
    except ImportError:                                    # still the generated file next to this test
        spec = importlib.util.spec_from_file_location("$name", HERE / "$name.py")
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
    return mod


def ctx(**opts):
    cfg = {"tasks": {"$name": dict(opts)}, "caps": {}, "protected": {"patterns": []}}
    return Ctx(cfg, "$name", apply=False)


def test_registered_with_the_contract():
    load()
    t = core.REGISTRY["$name"]
    assert (t.klass, t.tier) == ("$klass", "$tier") and callable(t.run) and t.timeout > 0


def test_result_is_one_short_ascii_line():
    load()
    res = core.REGISTRY["$name"].run(ctx())
    assert isinstance(res, core.Result) and res.status in ("ok", "info", "warn", "crit", "skipped", "error")
    assert res.summary.isascii() and "\\n" not in res.summary and len(res.summary) <= 140


def test_never_mutates_in_report_mode(tmp_path):
    load()
    victim = tmp_path / "old.txt"
    victim.write_text("keep me")
    c = ctx(path=str(tmp_path), max_age_days=0, candidates=[str(victim)])
    core.REGISTRY["$name"].run(c)
    assert victim.exists() and c.freed == 0                # report mode: ctx.act only audits "dry-run"
'''

_JOB = '''# Generated by `homelab-maint new job $name`. Append it to /etc/homelab-maint/jobs.toml (or put it in jobs.d/$name.toml where this
# build reads jobs.d). A job is an EXTERNAL command the umbrella schedules, gates, times out, logs, reports and alerts on. The command
# is an argv list (no shell); output goes to /var/log/homelab-maint/jobs/$name/<timestamp>.log with secrets scrubbed.
[[job]]
name = "$name"
title = "$title"
command = ["/usr/bin/true"]            # CHANGE ME: argv list, absolute path first ({self} = homelab-maint, {python} = python3); never a shell string
user = "root"                          # root | ohmz (the scheduler switches user with runuser)
schedule = "30 3 * * *"                # five-field cron in the host time zone, or @daily, "daily 03:30", "weekly sat 01:00", "every 15m"
mode = "managed"                       # managed: the tick runs it | observe: only shown, a legacy timer/cron still drives it | retired: never runs
source = "native"                      # "native": no legacy driver. An adapter job that REPLACES a legacy timer/cron line says retire = [...] instead
class = "P3"                           # P0 platform, P1 interactive, P2 batch, P3 best-effort (what to shed first under pressure)
heavy = false                          # true: serialised with every other heavy job (backups, big copies)
timeout_s = 600                        # TERM, then KILL of the whole process group; 0 = no limit
gates = []                             # busy gates that must be idle to START: comfyui, ollama, plex, immich, docker_build, backup, apt, gradle, any
# window = "02:00-05:00"               # optional: a catch-up run starts only inside this local-time window
# workdir = "/home/ohmz/project"
# env = { LANG = "C.UTF-8" }
success = { exit_codes = [0] }         # or { status_json = "/var/log/x/status.json", result_key = "result", ok_values = ["ok"], max_age_hours = 30 }
notify = { on_failure = "alert", on_success = "none" }      # on_success: none | maintenance
# retire = ["system:legacy-thing.timer"]   # only when this REPLACES a legacy driver ("user:ohmz:UNIT", "cron:ohmz:TAG"): the tick refuses to run it
#                                        # while that driver is enabled; then ship mode = "observe" and let `homelab-maint migrate cutover` flip it
'''

_PROBES = {
    "http": 'target = "http://127.0.0.1:8080/health"       # CHANGE ME: loopback or LAN URLs only unless external = true\nexpect = { status = [200], max_ms = 2000 }',
    "tcp": 'target = "127.0.0.1:5432"                       # CHANGE ME: host:port, connect only\nexpect = {}',
    "docker": 'target = "my-container"                        # CHANGE ME: container name, "@daemon" or "*"\nexpect = { state = "running" }',
    "systemd": 'target = "my-service.service"                # CHANGE ME\nexpect = { active = ["active"] }',
    "command": 'target = ["/usr/bin/test", "-d", "/media/x"]   # CHANGE ME: argv list, no shell; read-only commands only\nexpect = { ok_codes = [0] }',
    "file_age": 'target = "/var/lib/myapp/heartbeat"           # CHANGE ME: a file the app touches\nexpect = { max_age_s = 900 }',
    "json": 'target = "/var/lib/myapp/state.json"             # CHANGE ME: a JSON state file (or an http URL)\nexpect = { max_age_s = 900, json = [{ path = "status", equals = "ok" }] }',
}

_PROBE = '''# Generated by `homelab-maint new probe $name` (type $ptype). Put it in /etc/homelab-maint/probes.d/$name.toml (root-owned, not
# group/world-writable, or it is ignored) or append to probes.toml. Probes only READ; a timeout or an unparsable answer is a failure.
[[probe]]
name = "$name"
title = "$title"
type = "$ptype"
$body
interval_s = 300
timeout_s = 5
class = "P2"                           # P0 platform, P1 interactive, P2 batch, P3 best-effort
# severity = "warn"                    # crit | warn | info (info never pages); default follows the class
confirm = 2                            # consecutive failures before it counts as down
tags = ["app"]
# slo = 99.5                           # availability objective in percent over 30 days
# kuma_push_key = "my-service"         # also heartbeat the Uptime Kuma push monitor of that name (token in /etc/homelab-maint/kuma.toml)
'''


def _title(name: str, title: str | None) -> str:
    """A safe human title: it is substituted INSIDE string literals, so only a boring character set survives."""
    t = re.sub(r"[^A-Za-z0-9 ._()/+-]", "", title or name.replace("_", " ").replace("-", " ").capitalize()).strip()
    return t[:60] or name


def render_task(name: str, klass: str = "C0", tier: str = "check", title: str | None = None) -> str:
    _check_name("task", name)
    if klass not in KLASSES or tier not in TIERS:
        raise ValueError(f"klass must be one of {KLASSES} and tier one of {TIERS}")
    body = {"C0": _TASK_C0, "C1": _TASK_C1, "C2": _TASK_C2}[klass]
    text = Template(body).substitute(name=name, tier=tier, klass=klass, title=_title(name, title))
    compile(text, f"{name}.py", "exec")                       # what we hand out always loads
    return text


def render_task_test(name: str, klass: str = "C0", tier: str = "check") -> str:
    _check_name("task", name)
    text = Template(_TEST_STUB).substitute(name=name, klass=klass, tier=tier)
    compile(text, f"test_{name}.py", "exec")
    return text


def render_job(name: str, title: str | None = None) -> str:
    _check_name("job", name)
    text = Template(_JOB).substitute(name=name, title=_title(name, title))
    tomllib.loads(text)
    return text


def render_probe(name: str, ptype: str = "http", title: str | None = None) -> str:
    _check_name("probe", name)
    if ptype not in PROBE_TYPES:
        raise ValueError(f"probe type must be one of {PROBE_TYPES}")
    text = Template(_PROBE).substitute(name=name, ptype=ptype, title=_title(name, title), body=_PROBES[ptype])
    tomllib.loads(text)
    return text


def _check_name(kind: str, name: str) -> None:
    rx = TASK_RX if kind == "task" else NAME_RX
    if not isinstance(name, str) or not rx.fullmatch(name):
        raise ValueError(f"{kind} name must match {rx.pattern}" + (" (it becomes a Python file and a state file name)" if kind == "task" else ""))


# =================================================================== names already taken
_DECL_RX = re.compile(r"""(?:@task|register_task)\(\s*["']([a-z][a-z0-9_]*)["']""")


def known_task_names(conf_dir: Path | None = None) -> set[str]:
    """Registered tasks plus every task declared in the package or in plugins.d, found by SCANNING source (nothing is imported)."""
    names = set(core.REGISTRY)
    pkg = Path(__file__).resolve().parent
    files = [*sorted((pkg / "tasks").glob("*.py")), pkg / "routine.py"]
    files += sorted(((conf_dir or core.CONF_DIR) / "plugins.d").glob("*.py"))
    for f in files:
        with contextlib.suppress(OSError):
            names.update(_DECL_RX.findall(f.read_text(errors="replace")))
    return names


def _toml_names(files: list[Path], table: str) -> set[str]:
    out: set[str] = set()
    for f in files:
        with contextlib.suppress(OSError, tomllib.TOMLDecodeError):
            out.update(str(r.get("name")) for r in tomllib.loads(f.read_text()).get(table, []) if isinstance(r, dict))
    return out


def known_names(kind: str, conf_dir: Path | None = None) -> set[str]:
    c = conf_dir or core.CONF_DIR
    if kind == "task":
        return known_task_names(c)
    table, base = ("job", "jobs") if kind == "job" else ("probe", "probes")
    return _toml_names([c / f"{base}.toml", *sorted((c / f"{base}.d").glob("*.toml"))], table)


# =================================================================== is anything going to READ what we install?
# kind -> (module that consumes the directory, text that proves it does). Source is scanned, not imported: a broken module must not
# stop the generator, and a new build of the loader flips the answer by itself (no flag to forget).
_CONSUMERS = {"task": ("cli.py", "load_plugins"), "job": ("jobs.py", "jobs.d"), "probe": ("probes.py", "probes.d")}


def loader_reads(kind: str) -> bool:
    """True when this build's loader for `kind` reads the --install directory. A file that nothing reads is a silent no-op, which
    is worse than a refusal: the owner would believe the job/probe/task exists."""
    fname, needle = _CONSUMERS[kind]
    try:
        return needle in (Path(__file__).resolve().parent / fname).read_text(errors="replace")
    except OSError:
        return False


# =================================================================== writing files (secure)
def _write_new(path: Path, text: str, mode: int = 0o644) -> None:
    """Create `path` exclusively. O_EXCL: never overwrite; O_NOFOLLOW: never follow a planted symlink at the last component."""
    try:
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, mode)
    except FileExistsError:
        raise FileExistsError(f"{path} already exists; nothing was overwritten") from None
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.chmod(path, mode)


def create(kind: str, name: str, out_dir: Path | str = ".", *, klass: str = "C0", tier: str = "check", title: str | None = None,
           ptype: str = "http", install: bool = False, conf_dir: Path | None = None, trusted_uids: set[int] | None = None) -> list[Path]:
    """Write the generated file(s) and return their paths. Refuses to overwrite and refuses a name that is already taken."""
    if kind not in ("task", "job", "probe"):
        raise ValueError("kind must be task, job or probe")
    _check_name(kind, name)
    conf = Path(conf_dir) if conf_dir else core.CONF_DIR
    if name in known_names(kind, conf):
        raise FileExistsError(f"a {kind} named {name} already exists")
    if kind == "task":
        files = [(f"{name}.py", render_task(name, klass, tier, title)), (f"test_{name}.py", render_task_test(name, klass, tier))]
    elif kind == "job":
        files = [(f"{name}.toml", render_job(name, title))]
    else:
        files = [(f"{name}.toml", render_probe(name, ptype, title))]
    if install:
        sub = {"task": "plugins.d", "job": "jobs.d", "probe": "probes.d"}[kind]
        if not loader_reads(kind):
            instead = {"task": "copy the generated file into homelab_maint/tasks/ (cli.load_tasks must call scaffold.load_plugins for plugins.d)",
                       "job": "append the snippet to /etc/homelab-maint/jobs.toml", "probe": "append the snippet to /etc/homelab-maint/probes.toml"}[kind]
            raise NotImplementedError(f"this build does not read {sub}/ yet, so nothing would pick the file up: write it with --out and {instead}")
        target = conf / sub
        if kind == "task":
            files = files[:1]                                  # the test stub belongs in the repository, not in /etc
            problem = dir_problem(target, trusted_uids) if target.exists() else None
            if problem:
                raise PermissionError(f"{target}: {problem}")
        target.mkdir(parents=True, exist_ok=True, mode=0o755)
        out = target
    else:
        out = Path(out_dir)
        if out.is_symlink() or not out.is_dir():
            raise NotADirectoryError(f"{out} is not a directory")
    made: list[Path] = []
    try:
        for fname, text in files:
            p = out / fname
            _write_new(p, text)
            made.append(p)
    except OSError:
        for p in made:                                        # all or nothing
            with contextlib.suppress(OSError):
                p.unlink()
        raise
    return made


# =================================================================== plugin discovery
@dataclass
class PluginReport:
    loaded: dict[str, list[str]] = field(default_factory=dict)       # stem -> task names it registered
    rejected: dict[str, str] = field(default_factory=dict)           # stem -> why it was NOT executed or failed
    error_tasks: list[str] = field(default_factory=list)             # names of the plugin_<stem> error tasks registered
    skipped: list[str] = field(default_factory=list)                 # disabled, or already loaded in this process


_LOADED: dict[str, tuple] = {}              # path -> (st_dev, st_ino, st_mtime_ns, size, [tasks]) loaded in this process


def _trusted(trusted_uids: set[int] | None) -> set[int]:
    return {0, os.geteuid()} | set(trusted_uids or ())


def dir_problem(d: Path, trusted_uids: set[int] | None = None, check_ancestors: bool = True) -> str | None:
    """Why `d` cannot hold plugins, or None. A real directory, trusted owner, not group/world writable; its (resolved) ancestors
    must be trusted-owned and not group/world writable unless sticky."""
    trust = _trusted(trusted_uids)
    try:
        st = os.lstat(d)
    except OSError as exc:
        return f"cannot stat: {exc.strerror}"
    if stat.S_ISLNK(st.st_mode):
        return "is a symlink"
    if not stat.S_ISDIR(st.st_mode):
        return "is not a directory"
    if st.st_uid not in trust:
        return f"owned by uid {st.st_uid}, not root"
    if st.st_mode & 0o022:
        return f"is group/world writable (mode {stat.S_IMODE(st.st_mode):04o})"
    if check_ancestors:
        real = Path(os.path.realpath(d))
        for anc in real.parents:
            try:
                a = os.lstat(anc)
            except OSError:
                return f"cannot stat ancestor {anc}"
            if a.st_uid not in trust:
                return f"ancestor {anc} is owned by uid {a.st_uid}"
            if a.st_mode & 0o022 and not a.st_mode & stat.S_ISVTX:
                return f"ancestor {anc} is group/world writable"
    return None


def file_problem(st: os.stat_result, name: str, trusted_uids: set[int] | None = None, max_bytes: int = MAX_PLUGIN_BYTES) -> str | None:
    if not PLUGIN_FILE_RX.fullmatch(name):
        return "file name is not a plain module name ([A-Za-z][A-Za-z0-9_]*.py)"
    if stat.S_ISLNK(st.st_mode):
        return "is a symlink (refused even when the target is root-owned)"
    if not stat.S_ISREG(st.st_mode):
        return "is not a regular file"
    if st.st_uid not in _trusted(trusted_uids):
        return f"owned by uid {st.st_uid}, not root"
    if st.st_mode & 0o022:
        return f"is group/world writable (mode {stat.S_IMODE(st.st_mode):04o})"
    if st.st_size > max_bytes:
        return f"is larger than {max_bytes // 1024} KiB"
    return None


def _read_checked(path: Path, trusted_uids: set[int] | None, max_bytes: int) -> tuple[bytes | None, str]:
    """(source bytes, "") or (None, reason). The bytes come from the same descriptor that passed the checks."""
    try:
        before = os.lstat(path)
    except OSError as exc:
        return None, f"cannot stat: {exc.strerror}"
    why = file_problem(before, path.name, trusted_uids, max_bytes)
    if why:
        return None, why
    try:
        fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0))
    except OSError as exc:
        return None, f"cannot open: {exc.strerror}"
    try:
        st = os.fstat(fd)
        if (st.st_dev, st.st_ino) != (before.st_dev, before.st_ino):
            return None, "was replaced while being opened"
        why = file_problem(st, path.name, trusted_uids, max_bytes)
        if why:
            return None, why
        data = b""
        with os.fdopen(fd, "rb", closefd=False) as f:
            data = f.read(max_bytes + 1)
        if len(data) > max_bytes:
            return None, f"is larger than {max_bytes // 1024} KiB"
        return data, ""
    finally:
        os.close(fd)


class _ImportTimeout(BaseException):
    """BaseException on purpose, like core._Timeout: plugin code with `except Exception` must not swallow it."""


@contextlib.contextmanager
def _import_guard(seconds: float):
    """Bound the plugin's import time with SIGALRM (main thread only; elsewhere the guard is a no-op)."""
    if seconds <= 0 or threading.current_thread() is not threading.main_thread() or not hasattr(signal, "setitimer"):
        yield
        return

    def boom(_s, _f):
        raise _ImportTimeout()
    old = signal.signal(signal.SIGALRM, boom)
    prev = signal.getitimer(signal.ITIMER_REAL)
    signal.setitimer(signal.ITIMER_REAL, seconds)
    try:
        yield
    finally:
        signal.setitimer(signal.ITIMER_REAL, 0)
        signal.signal(signal.SIGALRM, old)
        if prev[0] > 0:
            signal.setitimer(signal.ITIMER_REAL, *prev)


def _reason(exc: BaseException) -> str:
    """One short ASCII line about an import failure: type, message, and the plugin line for a SyntaxError. No traceback."""
    if isinstance(exc, _ImportTimeout):
        return "import timed out"
    where = f" line {exc.lineno}" if isinstance(exc, SyntaxError) and exc.lineno else ""
    msg = re.sub(r"[^\x20-\x7e]", "?", str(exc).replace("\n", " "))[:70]
    return f"{type(exc).__name__}{where}: {msg}".strip(": ")


def _valid_task(t: Any, name: str) -> str | None:
    if not isinstance(t, Task) or t.name != name:
        return "registry entry is not a Task with a matching name"
    if not TASK_RX.fullmatch(name):
        return f"task name {name!r} must match {TASK_RX.pattern}"
    if t.klass not in KLASSES or t.tier not in TIERS:
        return f"task {name}: klass/tier must be one of {KLASSES} / {TIERS}"
    if not callable(t.run) or not isinstance(t.timeout, int) or isinstance(t.timeout, bool) or not 1 <= t.timeout <= 3600:
        return f"task {name}: run must be callable and timeout an integer 1..3600"
    return None


def _error_task(name: str, summary: str, plugin: str) -> None:
    def run(ctx) -> Result:                                   # noqa: ARG001
        return Result("error", summary[:140], {"plugin": plugin})
    core.REGISTRY[name] = Task(name, "C0", "check", run, title=f"Plugin {plugin}", timeout=10)


def _load_one(path: Path, data: bytes, report: PluginReport, timeout_s: float) -> None:
    stem = path.stem
    before = dict(core.REGISTRY)
    modname = f"homelab_plugin_{stem}"
    mod = types.ModuleType(modname)
    mod.__file__ = str(path)
    sys.modules[modname] = mod                                # dataclasses and pickling look the module up by name
    err = ""
    try:
        with _import_guard(timeout_s):
            code = compile(data, str(path), "exec")
            exec(code, mod.__dict__)                          # noqa: S102  (root-owned code by construction)
    except KeyboardInterrupt:
        raise
    except BaseException as exc:                              # noqa: BLE001  (SystemExit, a hung import, anything)
        err = _reason(exc)
    added = [n for n in core.REGISTRY if n not in before]
    clobbered = [n for n in before if core.REGISTRY.get(n) is not before[n]]
    for n in clobbered:                                       # a plugin can never replace or remove a builtin
        core.REGISTRY[n] = before[n]
    if clobbered and not err:
        err = f"tried to replace or remove task(s): {', '.join(sorted(clobbered))[:60]}"
    if not err:
        for n in added:
            bad = _valid_task(core.REGISTRY[n], n)
            if bad:
                err = bad[:100]
                break
    if err:
        for n in added:                                       # roll back everything this plugin registered
            core.REGISTRY.pop(n, None)
        sys.modules.pop(modname, None)
        report.rejected[stem] = err
        return
    report.loaded[stem] = added
    st = os.stat(path)
    _LOADED[str(path)] = (st.st_dev, st.st_ino, st.st_mtime_ns, st.st_size, added)


def load_plugins(plugin_dir: Path | str | None = None, *, trusted_uids: set[int] | None = None, timeout_s: float = IMPORT_TIMEOUT_S,
                 disabled: tuple[str, ...] = (), max_bytes: int = MAX_PLUGIN_BYTES, register_errors: bool = True,
                 check_ancestors: bool = True) -> PluginReport:
    """Discover, vet and import /etc/homelab-maint/plugins.d/*.py. Never raises; never lets one plugin affect another."""
    d = Path(plugin_dir) if plugin_dir else core.CONF_DIR / "plugins.d"
    rep = PluginReport()
    if not os.path.lexists(d):
        return rep                                            # no plugins.d: nothing to do (the normal case)
    why = dir_problem(d, trusted_uids, check_ancestors)
    if why:
        rep.rejected["(directory)"] = f"{d}: {why}"
        if register_errors:
            _error_task("plugins_dir", f"plugins.d ignored: {why}"[:140], "(directory)")
            rep.error_tasks.append("plugins_dir")
        return rep
    try:
        names = sorted(os.listdir(d))
    except OSError as exc:
        rep.rejected["(directory)"] = f"cannot list: {exc.strerror}"
        return rep
    for fname in names:
        if fname.startswith(".") or fname == "__pycache__" or not fname.endswith(".py"):
            continue
        path, stem = d / fname, fname[:-3]
        if stem in disabled:
            rep.skipped.append(stem)
            continue
        data, why = _read_checked(path, trusted_uids, max_bytes)
        if data is None:
            rep.rejected[stem] = why
            continue
        st = os.stat(path)
        prev = _LOADED.get(str(path))
        if prev and all(n in core.REGISTRY for n in prev[4]):
            # already imported by this process: never exec twice (a changed file waits for the next run; an in-process reload
            # would re-register its own tasks and look like an attempt to replace them)
            rep.loaded[stem] = list(prev[4])
            rep.skipped.append(stem)
            continue
        _load_one(path, data, rep, timeout_s)
    if register_errors:
        for stem, why in rep.rejected.items():
            if stem == "(directory)":
                continue
            name = f"plugin_{stem}"
            if name in core.REGISTRY:
                continue                                      # never shadow a real task with an error placeholder
            _error_task(name, f"plugin {stem}.py: {why}", stem)
            rep.error_tasks.append(name)
    return rep


def reset_loaded() -> None:
    """Forget what this process loaded (tests, or a long-lived process that wants a fresh scan)."""
    _LOADED.clear()


# =================================================================== CLI
def main(argv: list[str] | None = None) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="homelab-maint", description="scaffold tasks/jobs/probes and inspect plugins")
    sub = ap.add_subparsers(dest="cmd", required=True)
    n = sub.add_parser("new", help="generate a ready-to-edit task, job or probe")
    n.add_argument("kind", choices=("task", "job", "probe"))
    n.add_argument("name")
    n.add_argument("--klass", choices=KLASSES, default="C0", help="tasks: C0 read-only, C1 safe cleaner, C2 plan+approval")
    n.add_argument("--tier", choices=TIERS, default="check")
    n.add_argument("--type", dest="ptype", choices=PROBE_TYPES, default="http", help="probes only")
    n.add_argument("--title")
    n.add_argument("--out", default=".", help="directory to write into (default: current)")
    n.add_argument("--install", action="store_true", help="write under /etc/homelab-maint (plugins.d / jobs.d / probes.d) instead")
    sub.add_parser("plugins", help="load plugins.d exactly as the runner would and report what was loaded or refused")
    a = ap.parse_args(argv)
    if a.cmd == "plugins":
        rep = load_plugins()
        for stem, tasks in rep.loaded.items():
            print(f"loaded    {stem}.py: {', '.join(tasks) or '(no tasks registered)'}")
        for stem, why in rep.rejected.items():
            print(f"REFUSED   {stem}: {why}")
        if not (rep.loaded or rep.rejected):
            print("no plugins (plugins.d is absent or empty)")
        return 1 if rep.rejected else 0
    try:
        made = create(a.kind, a.name, a.out, klass=a.klass, tier=a.tier, title=a.title, ptype=a.ptype, install=a.install)
    except (ValueError, FileExistsError, NotADirectoryError, PermissionError, NotImplementedError, OSError) as exc:
        print(f"homelab-maint new: {exc}", file=sys.stderr)
        return 2
    for p in made:
        print(f"created {p}")
    hint = {"task": "edit it; move {n}.py to homelab_maint/tasks/ (or, as root, copy it to /etc/homelab-maint/plugins.d/) and test_{n}.py to tests/; "
                    "then: python3 -m pytest tests/test_{n}.py -q",
            "job": "edit command/schedule, then: homelab-maint schedule   (the unified schedule shows when it runs next)",
            "probe": "edit the target, then: python3 -m homelab_maint.probes validate"}[a.kind].format(n=a.name)
    print("next: " + hint)
    return 0


if __name__ == "__main__":
    sys.exit(main())
